apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiZFc1cFkzVnRNak02WjJod1h6WlNlbGd6ZWpGamN6aEVVMFZrVkhrMlQwUnBkekJPT1hSV2QwRktTRE5GTlRoQ1JnPT0iCiAgICAgICAgICAgICAgICB9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
